"""Generated grpc-gateway code declares routes; we read the declaration.

The path in a `*.pb.gw.go` file is never a literal — it is a compiled
pattern, an opcode list against a string pool — so every regex that looks
for a quoted path finds nothing. That is why 104 `google.api.http`
bindings in the reference corpus matched zero HTTP contracts: the graph
had the gRPC operations and none of the endpoints serving them.

The opcode fixtures here are copied from real generated files in
grpc-ecosystem/grpc-gateway, not invented, because a decoder tested only
against encodings I wrote myself proves that I am self-consistent rather
than that I read the format correctly.
"""

from tracekite.services.grpc_gateway_routes import (
    decode_pattern, extract_gateway_routes,
)


class TestDecodePattern:
    """Real ops/pool pairs from examples/internal/proto/examplepb."""

    def test_all_literal_segments(self):
        assert decode_pattern([2, 0, 2, 1, 2, 2],
                              ["v2", "example", "empty"]) == "/v2/example/empty"

    def test_a_trailing_capture(self):
        assert decode_pattern([2, 0, 2, 1, 1, 0, 4, 1, 5, 2],
                              ["v1", "camel_case", "state"]) == \
            "/v1/camel_case/{state}"

    def test_several_captures(self):
        ops = [2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3,
               1, 0, 4, 1, 5, 4, 1, 0, 4, 1, 5, 5]
        pool = ["v1", "example", "snake", "who", "what", "where"]
        assert decode_pattern(ops, pool) == \
            "/v1/example/snake/{who}/{what}/{where}"

    def test_a_dotted_field_path_stays_one_segment(self):
        ops = [2, 0, 2, 1, 2, 2, 2, 3, 2, 4, 2, 5, 1, 0, 4, 1, 5, 6]
        pool = ["v1", "example", "a_bit_of_everything", "params", "get",
                "nested_enum", "single_nested.ok"]
        assert decode_pattern(ops, pool) == (
            "/v1/example/a_bit_of_everything/params/get/nested_enum/"
            "{single_nested.ok}")

    def test_an_unknown_opcode_yields_nothing(self):
        """A path assembled from a half-understood instruction stream would
        be a fabricated endpoint, which is worse than a missing one."""
        assert decode_pattern([2, 0, 9, 1], ["v1", "x"]) is None

    def test_an_out_of_range_pool_index_yields_nothing(self):
        assert decode_pattern([2, 5], ["v1"]) is None

    def test_an_odd_ops_list_yields_nothing(self):
        assert decode_pattern([2, 0, 2], ["v1", "x"]) is None

    def test_no_segments_yields_nothing(self):
        assert decode_pattern([], []) is None


GENERATED = '''
// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
package examplepb

var (
\tpattern_EchoService_Echo_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "example", "id"}, ""))
\tpattern_Camel_CaseService_GetStatus_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "camel_case", "state"}, ""))
)

func RegisterEchoServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux) error {
\tmux.Handle(http.MethodPost, pattern_EchoService_Echo_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
\t})
\tmux.Handle(http.MethodGet, pattern_Camel_CaseService_GetStatus_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
\t})
\treturn nil
}
'''


class TestExtraction:
    def routes(self, path="api/echo.pb.gw.go", content=GENERATED):
        return extract_gateway_routes(path, content)

    def test_method_path_and_operation(self):
        by_path = {r.path: r for r in self.routes()}
        echo = by_path["/v1/example/{id}"]
        assert echo.method == "POST"
        assert echo.framework == "grpc-gateway"
        assert echo.handler_name == "EchoService/Echo"
        assert echo.attrs["grpc_service"] == "EchoService"
        assert echo.attrs["grpc_rpc"] == "Echo"

    def test_a_service_name_containing_underscores(self):
        """`Camel_CaseService_GetStatus_0` must not split into
        `Camel` / `CaseService_GetStatus`."""
        [route] = [r for r in self.routes()
                   if r.path == "/v1/camel_case/state"]
        assert route.attrs["grpc_service"] == "Camel_CaseService"
        assert route.attrs["grpc_rpc"] == "GetStatus"

    def test_only_generated_gateway_files_are_read(self):
        assert extract_gateway_routes("api/echo.go", GENERATED) == []

    def test_a_handle_whose_pattern_is_unreadable_is_skipped(self):
        content = GENERATED.replace("[]int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}",
                                    "[]int{2, 0, 77, 1}")
        paths = {r.path for r in self.routes(content=content)}
        assert "/v1/camel_case/state" in paths      # the readable one survives
        assert len(paths) == 1                       # the other is declined

    def test_lines_are_the_registration_site(self):
        for route in self.routes():
            assert route.line > 0
            assert "mux.Handle" in GENERATED.split("\n")[route.line - 1]
