"""A dependency claim cites the line that declares the package.

Every `lib` claim used to cite `manifest:1`. On one 312-file repository that
put 376 of 942 citations on a line that did not mention the package — in the
resolved `requirements.txt` files, line 1 is
`# This file was autogenerated by uv`.

The trap that shapes the locator: a resolved requirements file names each
package twice, once where it is pinned and once in a `# via <name>`
provenance comment, and the comment frequently comes FIRST. Searching for
the name finds the comment; only searching for the name where a declaration
puts it finds the pin.
"""

from tracekite.services.manifest_lines import declaration_line, declaration_line_any

REQUIREMENTS = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in -o requirements.txt
cachetools==5.3.2
    # via google-auth
certifi==2024.7.4
    # via requests
google-auth==2.23.4
    # via google-api-core
"""

GO_MOD = """\
module github.com/acme/frontend

go 1.25.0

require (
\tgithub.com/gorilla/mux v1.8.1
\tgoogle.golang.org/grpc v1.82.0
)
"""


class TestDeclarationBeatsMention:
    def test_a_via_comment_does_not_win_over_the_pin(self):
        """`# via google-auth` is line 4; the pin is line 7."""
        assert declaration_line(REQUIREMENTS, "google-auth") == 7

    def test_a_plain_pin_is_found(self):
        assert declaration_line(REQUIREMENTS, "certifi") == 5
        assert declaration_line(REQUIREMENTS, "cachetools") == 3

    def test_a_package_named_only_in_a_comment_is_not_declared(self):
        assert declaration_line(REQUIREMENTS, "requests") == 0


class TestGrammars:
    def test_go_module_paths(self):
        assert declaration_line(GO_MOD, "github.com/gorilla/mux") == 6
        assert declaration_line(GO_MOD, "google.golang.org/grpc") == 7

    def test_quoted_json_key(self):
        content = '{\n  "dependencies": {\n    "express": "^4.18.0"\n  }\n}'
        assert declaration_line(content, "express") == 3

    def test_maven_element_text(self):
        content = "<project>\n  <dependency>\n    <artifactId>guava</artifactId>\n"
        assert declaration_line(content, "guava") == 3

    def test_msbuild_attribute_value(self):
        """`.csproj` names the package in an attribute, not element text."""
        content = ("<Project>\n  <ItemGroup>\n"
                   "    <PackageReference Include=\"Npgsql\" Version=\"10.0.3\" />\n")
        assert declaration_line(content, "Npgsql") == 3

    def test_a_sibling_project_reference_counts_on_its_stem(self):
        """`Include="..\\src\\cartservice.csproj"` declares `cartservice`."""
        content = ("<Project>\n  <ItemGroup>\n"
                   "    <ProjectReference Include=\"..\\src\\cartservice.csproj\" />\n")
        assert declaration_line(content, "cartservice") == 3

    def test_keyword_then_quoted_name(self):
        assert declaration_line("source 'x'\ngem 'puma'\n", "puma") == 2

    def test_extras_and_operators_still_count_as_a_declaration(self):
        assert declaration_line("uvicorn[standard]>=0.30\n", "uvicorn") == 1

    def test_a_longer_name_is_not_matched_by_its_prefix(self):
        """`grpcio` must not claim the `grpcio-health-checking` line."""
        content = "grpcio-health-checking==1.0\ngrpcio==1.76.0\n"
        assert declaration_line(content, "grpcio") == 2


class TestFallback:
    def test_absent_name_yields_zero(self):
        assert declaration_line(REQUIREMENTS, "not-here") == 0

    def test_empty_inputs_yield_zero(self):
        assert declaration_line("", "x") == 0
        assert declaration_line("x==1", "") == 0

    def test_any_prefers_the_first_name_that_is_declared(self):
        assert declaration_line_any(GO_MOD, "github.com/gorilla/mux", "mux") == 6
        assert declaration_line_any(GO_MOD, "absent", "google.golang.org/grpc") == 7
