"""Test/vendored/generated classification."""

import pytest

from evigraph.services.claims import ContractClaim
from evigraph.services.file_classifier import classify, has_generated_header


class TestTest:
    @pytest.mark.parametrize("path", [
        "src/test/java/AppTest.java", "src/test/resources/application.yaml",
        "tests/test_client.py", "app/__tests__/api.test.ts",
        "internal/handler_test.go", "spec/models/user_spec.rb",
        "e2e/checkout.spec.ts", "testdata/fixtures.json",
        "src/main/java/AppTests.cs",
    ])
    def test_test_paths(self, path):
        assert classify(path).is_test is True

    @pytest.mark.parametrize("path", [
        "src/main/java/App.java", "app/services/latest.py",
        "src/attestation/Attestation.java",   # contains "test" as a substring
        "src/contest/Contest.kt",
    ])
    def test_production_paths_not_flagged(self, path):
        assert classify(path).is_test is False


class TestVendored:
    @pytest.mark.parametrize("path", [
        "vendor/github.com/x/y/client.go", "node_modules/axios/index.js",
        "third_party/lib/api.py", "app/vendored/sdk.ts",
    ])
    def test_vendored_paths(self, path):
        assert classify(path).is_vendored is True

    def test_own_source_not_vendored(self):
        assert classify("src/client/api.ts").is_vendored is False


class TestGenerated:
    @pytest.mark.parametrize("path", [
        "gen/proto/orders.pb.go", "api/orders_pb2.py", "api/orders_pb2_grpc.py",
        "generated/client.ts", "src/__generated__/graphql.ts",
        "Protos/OrdersGrpc.cs", "lib/models.g.dart",
        "src/api.generated.ts",
    ])
    def test_generated_paths(self, path):
        assert classify(path).is_generated is True

    @pytest.mark.parametrize("header", [
        "// Code generated by protoc-gen-go. DO NOT EDIT.",
        "/* @generated */",
        "# Generated by the protocol buffer compiler.  DO NOT EDIT!",
        "// Generated by orval",
        "// THIS FILE IS AUTO-GENERATED",
    ])
    def test_generated_headers(self, header):
        assert has_generated_header(header + "\npackage main\n") is True

    def test_header_only_checked_near_the_top(self):
        # A mention 200 lines down is prose, not a marker.
        body = "\n".join(["x"] * 200) + "\n// @generated\n"
        assert has_generated_header(body) is False

    def test_generated_is_not_excluded_from_linking(self):
        # A protobuf stub is the best evidence a repo consumes a contract.
        assert classify("gen/orders.pb.go").excluded_from_linking is False
        assert classify("gen/orders.pb.go").reason == "generated"


class TestClaimGating:
    def test_test_claims_are_stored_but_unmatchable(self):
        claim = ContractClaim(repo_id="r", kind="http", direction="provides",
                              key="GET:/x", evidence=["src/test/A.java:1"],
                              provenance="test")
        assert claim.matchable is False

    def test_vendored_claims_unmatchable(self):
        claim = ContractClaim(repo_id="r", kind="http", direction="provides",
                              key="GET:/x", evidence=["vendor/a.go:1"],
                              provenance="vendored")
        assert claim.matchable is False

    def test_generated_claims_stay_matchable(self):
        claim = ContractClaim(repo_id="r", kind="http", direction="consumes",
                              key="httpcall:GET:/x", evidence=["gen/c.ts:1"],
                              provenance="generated")
        assert claim.matchable is True

    def test_production_claims_matchable(self):
        claim = ContractClaim(repo_id="r", kind="http", direction="provides",
                              key="GET:/x", evidence=["src/main/A.java:1"])
        assert claim.matchable is True


class TestProvenanceStamping:
    def test_stamped_from_evidence_path_automatically(self):
        from types import SimpleNamespace
        from evigraph.services.ingest_claims import emit_source_claims
        from evigraph.services.ingest_source import IngestSink

        sink = IngestSink()
        emit_source_claims(
            "r", SimpleNamespace(path="src/test/java/AppTest.java", language="java"),
            'restTemplate.getForObject("http://orders-service/v1/x", String.class);',
            [], "f", sink)
        claims = [n for n in sink.nodes if n.type == "ContractClaim"]
        assert claims, "fixture should still produce visible claims"
        assert all(c.extra_props["provenance"] == "test" for c in claims)
        assert all(c.extra_props["matchable"] is False for c in claims)

    def test_production_file_has_empty_provenance(self):
        from types import SimpleNamespace
        from evigraph.services.ingest_claims import emit_source_claims
        from evigraph.services.ingest_source import IngestSink

        sink = IngestSink()
        emit_source_claims(
            "r", SimpleNamespace(path="src/main/java/Client.java", language="java"),
            'restTemplate.getForObject("http://orders-service/v1/x", String.class);',
            [], "f", sink)
        claims = [n for n in sink.nodes if n.type == "ContractClaim"]
        assert all(c.extra_props["provenance"] == "" for c in claims)
        assert all(c.extra_props["matchable"] is True for c in claims)
