"""The line of a manifest that declares a package, not one that mentions it.

Dependency claims used to cite `manifest:1` for every package, so a reader
following the receipt for `certifi` landed on
`# This file was autogenerated by uv` and had to find the real line
themselves. On one 312-file repository that was 376 of 942 citations
pointing somewhere the claim could not be confirmed.

Finding the line is not a search for the name: a resolved
`requirements.txt` mentions each package again in `# via <name>` provenance
comments, and in the file that motivated this the first mention of
`google-auth` is such a comment four lines above the `google-auth==` that
actually declares it. So a mention is never enough — the name has to appear
where a declaration puts it.

Every manifest grammar this reads puts the name in one of three positions,
which is what makes one locator serve all of them rather than fifteen:

    name==1.2  name = "1.2"  name:            leading, any delimiter
    "name": "^1.2"                           quoted key
    <artifactId>name</artifactId>            element text
    gem "name"   require "name"              keyword then quoted name

Returns 0 when the name is not declared anywhere, which the caller reads as
"keep the citation you already have" rather than as line zero.
"""

import re

_COMMENT = ("#", "//", "--", ";")
# What may follow a name where it is declared: a version operator, an extras
# bracket, an assignment, a separator, or nothing.
_DELIM = set("=<>~!^@[]{}(),;:\"' \t/*")


def _uncommented(line: str) -> str:
    """The part of a line before any comment marker.

    A `# via requests` line is provenance, not a declaration, so a name
    found only there must not win.
    """
    cut = len(line)
    for marker in _COMMENT:
        found = line.find(marker)
        if found != -1:
            cut = min(cut, found)
    return line[:cut]


def _attr_values(lowered: str, quote: str) -> list[str]:
    """Every `=<quote>value<quote>` on a line."""
    values, at = [], lowered.find("=" + quote)
    while at != -1:
        end = lowered.find(quote, at + 2)
        if end == -1:
            break
        values.append(lowered[at + 2:end])
        at = lowered.find("=" + quote, end)
    return values


def _declares(text: str, name: str) -> bool:
    """Does this line put `name` where a declaration puts it?"""
    stripped = text.strip()
    if not stripped:
        return False
    lowered = stripped.lower()
    target = name.lower()

    # leading: `certifi==2024.7.4`, `github.com/gorilla/mux v1.8.1`
    if lowered.startswith(target):
        rest = stripped[len(name):]
        if not rest or rest[0] in _DELIM:
            return True

    # quoted key: `"express": "^4.18.0"`, `'rails': '7.0'`
    for quote in ("\"", "'"):
        if lowered.startswith(quote + target + quote):
            return True

    # element text: `<artifactId>guava</artifactId>`
    if f">{target}<" in lowered:
        return True

    # attribute value: `<PackageReference Include="Grpc.AspNetCore" .../>`
    # The attribute is not named because the grammars disagree — MSBuild uses
    # Include, others use name or id — and the position is the signal. A
    # path-valued attribute counts on its stem, because a sibling project is
    # declared as `Include="..\src\cartservice.csproj"` and the dependency
    # it names is `cartservice`.
    for quote in ("\"", "'"):
        if f"={quote}{target}{quote}" in lowered:
            return True
        for value in _attr_values(lowered, quote):
            stem = value.replace("\\", "/").rsplit("/", 1)[-1]
            if stem == target or stem.rsplit(".", 1)[0] == target:
                return True

    # keyword then quoted name: `gem "puma"`, `require "sinatra"`
    for quote in ("\"", "'"):
        marker = quote + target + quote
        at = lowered.find(marker)
        if at > 0:
            before = stripped[:at].strip()
            # a bare keyword, not an arbitrary expression containing a string
            if before and before.replace("_", "").replace("-", "").isalpha():
                return True
    return False


def declaration_line(content: str, name: str) -> int:
    """1-based line declaring `name`, or 0 when it is never declared.

    Ties go to the first declaration: a manifest that pins a package twice
    is a fact about the manifest, and the earlier line is the one a reader
    scrolling from the top reaches.
    """
    if not content or not name:
        return 0
    lines = content.split("\n")
    for number, line in enumerate(lines, start=1):
        if _declares(_uncommented(line), name):
            return number
    return 0


_TAIL = re.compile(r"[^A-Za-z0-9_.+-]")


def declaration_line_any(content: str, *names: str) -> int:
    """First line declaring any of `names`, preferring the order given.

    A go.mod row is the full module path while the claim key keeps only the
    last segment, so the caller offers both and the most specific wins.
    """
    for name in names:
        if not name:
            continue
        found = declaration_line(content, name)
        if found:
            return found
    return 0
