"""Classify files as test, vendored or generated.

Three distinct reasons a file's claims should not be treated as production facts:

- **test** — a fixture URL like ``http://localhost:8080`` is not a dependency,
  and letting it into the env index makes R9 see contradictory values and
  suppress the real edge.
- **vendored** — third-party source copied into the tree. Its endpoints belong
  to someone else's service and would attribute their API to this repo.
- **generated** — protobuf stubs, OpenAPI clients and GraphQL codegen output.
  These are *not* excluded: they are the most reliable contract evidence there
  is. They are tagged so a generated stub can be treated as a client call site
  rather than a hand-written one, and so they never look like authored code.
"""

import re
from dataclasses import dataclass

# Directory segments. Matched as whole segments, never substrings, so a service
# named `attestation` is not mistaken for a test tree.
TEST_DIRS = frozenset({
    "test", "tests", "testing", "spec", "specs", "__tests__", "__test__",
    "e2e", "integration-tests", "it", "acceptance", "fixtures", "testdata",
    "mocks", "__mocks__", "stubs", "cypress", "playwright",
})
VENDOR_DIRS = frozenset({
    "vendor", "vendored", "third_party", "thirdparty", "third-party",
    "node_modules", "bower_components", "external", "deps", "packages",
    "site-packages", "eggs", ".venv", "venv",
})
GENERATED_DIRS = frozenset({
    "generated", "gen", "__generated__", "autogen", "auto-generated",
    "build", "target", "out", "dist", "obj", "bin",
    "protos-gen", "pb", "pb-gen", "graphql-generated",
})

# Filename patterns.
_TEST_FILE = re.compile(
    r"(^|[._-])(test|tests|spec|specs|it)([._-]|$)"
    r"|^test_|_test\.|\.test\.|\.spec\.|Test\.java$|Tests\.cs$|_spec\.rb$",
    re.IGNORECASE)
_GENERATED_FILE = re.compile(
    r"\.pb\.(go|py|ts|js|cc|h)$|_pb2(_grpc)?\.py$|\.pb\.gw\.go$"
    r"|_grpc\.pb\.(go|cc|h)$|Grpc\.cs$|\.g\.(dart|cs|ts)$"
    r"|\.generated\.[a-z]+$|\.gen\.[a-z]+$"
    r"|^schema\.graphql$|\.generated\.graphql$"
    r"|(^|/)api\.schemas\.ts$|(^|/)api\.ts$",
    re.IGNORECASE)

# Header markers, checked in the first few lines only. This is the canonical
# signal — Go, protoc, OpenAPI Generator and GraphQL Codegen all emit one.
_GENERATED_HEADER = re.compile(
    r"^//\s*Code generated .* DO NOT EDIT\.?$"
    r"|@generated\b"
    r"|Generated by the protocol buffer compiler"
    r"|DO NOT EDIT THIS FILE"
    r"|This file was automatically generated"
    r"|Generated by openapi-generator"
    r"|Generated by orval"
    r"|THIS FILE IS AUTO-GENERATED",
    re.IGNORECASE | re.MULTILINE)
_HEADER_LINES = 12


@dataclass(frozen=True)
class FileClass:
    is_test: bool = False
    is_vendored: bool = False
    is_generated: bool = False

    @property
    def excluded_from_linking(self) -> bool:
        """Whether claims from this file are facts about *this* system.

        Generated code is deliberately still linked: a protobuf stub is the
        best evidence a repo consumes a contract.
        """
        return self.is_test or self.is_vendored

    @property
    def reason(self) -> str:
        if self.is_vendored:
            return "vendored"
        if self.is_test:
            return "test"
        if self.is_generated:
            return "generated"
        return ""


def _segments(path: str) -> list[str]:
    return [s for s in path.lower().replace("\\", "/").split("/") if s]


def is_vendored_path(path: str) -> bool:
    return any(segment in VENDOR_DIRS for segment in _segments(path)[:-1])


def is_test_path(path: str) -> bool:
    segments = _segments(path)
    if any(segment in TEST_DIRS for segment in segments[:-1]):
        return True
    return bool(segments and _TEST_FILE.search(segments[-1]))


def is_generated_path(path: str) -> bool:
    segments = _segments(path)
    if any(segment in GENERATED_DIRS for segment in segments[:-1]):
        return True
    return bool(_GENERATED_FILE.search(path))


def has_generated_header(content: str) -> bool:
    """Whether the file declares itself generated in its first lines."""
    if not content:
        return False
    head = "\n".join(content.split("\n", _HEADER_LINES)[:_HEADER_LINES])
    return bool(_GENERATED_HEADER.search(head))


def classify(path: str, content: str = "") -> FileClass:
    """Classify one file. Content is optional; the header check needs it."""
    return FileClass(
        is_test=is_test_path(path),
        is_vendored=is_vendored_path(path),
        is_generated=is_generated_path(path) or has_generated_header(content),
    )
