"""The generated tail of confidence.yml, and the gaps it must cover.

`write_measured()` appends/replaces a clearly-delimited generated block at
the END of confidence.yml — the measured P/R rows, plus the derived
constants table when calibrate supplies one. The hand-authored flat
tier table above the marker is preserved byte-for-byte: `ctx.conf()` reads
it and PyYAML would drop its comments, so only marker-to-EOF is rewritten,
parse-checked, and swapped in atomically.

`coverage_gaps()` lists every served flat tier with no measured row —
invariant 7's teeth: a tier serving `active` edges on a confidence nobody
measured.
"""

import os
import tempfile
from datetime import datetime, timezone

import yaml

from adduce.services.calibration_tiers import flat_sections

MEASURED_MARKER = "# --- MEASURED (generated by tools/calibrate.py; do not edit) ---"
DEFAULT_CORPUS = "fixtures-v1"


def write_measured(results: dict, config_path: str,
                   corpus: str = DEFAULT_CORPUS,
                   derived_lines: list[str] | None = None) -> None:
    """Rewrite the generated block: measured rows, then any derived table.

    Both live inside the same marker-to-EOF region so a plain calibrate run
    can never strand a stale `derived:` section behind — everything below
    the marker is regenerated together or not at all.
    """
    with open(config_path, "r", encoding="utf-8") as handle:
        original = handle.read()
    base = original.split(MEASURED_MARKER)[0].rstrip("\n") + "\n"

    lines = [MEASURED_MARKER, "measured:", f"  corpus: {corpus}",
             f"  at: '{datetime.now(timezone.utc).isoformat(timespec='seconds')}'",
             "  rows:"]
    for section in sorted(k for k in results if not k.startswith("_")):
        for tier in sorted(results[section]):
            row = results[section][tier]
            lines.append(
                f"    {section}.{tier}: {{precision: {row['precision']}, "
                f"precision_lo: {row['precision_lo']}, "
                f"precision_hi: {row['precision_hi']}, "
                f"recall: {row['recall']}, support: {row['support']}, "
                f"fp: {row['fp']}}}")
    lines.extend(derived_lines or [])
    text = base + "\n" + "\n".join(lines) + "\n"

    parsed = yaml.safe_load(text)  # parse-check before touching the file
    before = yaml.safe_load(original) or {}
    for key, value in before.items():
        if key not in ("measured", "derived") and parsed.get(key) != value:
            raise RuntimeError(
                f"write_measured would alter flat key {key!r}; refusing to "
                f"write {config_path}")

    directory = os.path.dirname(os.path.abspath(config_path))
    fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".confidence-",
                                    suffix=".yml")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(tmp_path, config_path)
    except BaseException:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise


def coverage_gaps(results: dict, config_path: str) -> list[str]:
    """Every flat tier in confidence.yml with NO measured row.

    This is the harness's own exit criteria: invariant 7 says these tiers are
    serving `active` edges on an unmeasured confidence.
    """
    with open(config_path, "r", encoding="utf-8") as handle:
        table = yaml.safe_load(handle) or {}
    gaps = []
    # Sections derived from the config, not listed: a hard-coded tuple
    # predating R10/R11 left seven served tiers invisible to this gate.
    for section in flat_sections(table):
        tiers = table.get(section)
        if not isinstance(tiers, dict):
            continue
        for tier, served in tiers.items():
            if not isinstance(served, (int, float)) or isinstance(served, bool):
                continue
            if tier not in (results.get(section) or {}):
                gaps.append(f"{section}.{tier}")
    return sorted(gaps)
